### PR TITLE
ci: tests arm64 via Apple Silicon

### PR DESCRIPTION
**Pull request by codefromthecrypt**
See https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
oops can't do it https://github.com/orgs/community/discussions/69211

**Comment by codefromthecrypt** [comment]
I emailed https://www.flyci.net/ in case we can get one of their runners for our two docker-only repos (this and docker-java)

**Comment by codefromthecrypt** [comment]
flyci got back immediately, so I enabled for this repo and docker-java (to conserve minutes). I'll update the build-bin/README.md and email zipkin-dev if it works, to record the details.

**Comment by codefromthecrypt** [comment]
@kgantchev sorry if it is documented somewhere obvious I missed, but does flyci not support running docker also?

**Comment by kgantchev** [comment]
@codefromthecrypt unfortunately, nested virtualization (e.g. Docker) is currently not supported by the Apple Virtualization Framework that we are using under the hood.

**Comment by codefromthecrypt** [comment]
@kgantchev no biggie. it was very easy to try this, and I can see a lot of value for flyci in other projects. cheers!

**Comment by kgantchev** [comment]
@codefromthecrypt no problem. Please feel free to contact me should you have any other questions.

**Pull request closed without merging**
